### ISSUE TITLE
Support for defining options through a config file

### ISSUE THREAD

**Issue by friederbluemle** [cameronhunter/prettier-package-json#27]
Right now it is possible to customize the behavior through command line arguments. It would be nice if there was also an option to define a custom config file (and maybe use a default `.ppjrc.js` or similar if one exists).

**Comment by cameronhunter** [comment]
I've added this feature in `v2.5.0`. Check out the [README](https://github.com/cameronhunter/prettier-package-json#options) for how to use it.
